onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix hexadecimal /tb/clkq
add wave -noupdate -radix hexadecimal /tb/clk125
add wave -noupdate -radix hexadecimal /tb/clk125_div2
add wave -noupdate -radix hexadecimal /tb/clk125_div4
add wave -noupdate -radix hexadecimal /tb/reset
add wave -noupdate -radix hexadecimal /tb/cnt_rd
add wave -noupdate -radix hexadecimal /tb/cnt_wr
add wave -noupdate -radix hexadecimal /tb/tx_cnt
add wave -noupdate -radix hexadecimal /tb/lfsr_reg
add wave -noupdate -radix hexadecimal /tb/bits
add wave -noupdate -radix hexadecimal /tb/o_interp_ce
add wave -noupdate -radix hexadecimal /tb/o_interp_ce_w1
add wave -noupdate -radix hexadecimal /tb/sm_qam_ce
add wave -noupdate -radix decimal /tb/o_samplesi
add wave -noupdate -radix decimal /tb/o_samplesq
add wave -noupdate -radix decimal /tb/rcc_up_filter_inst/clk
add wave -noupdate -radix decimal /tb/rcc_up_filter_inst/reset
add wave -noupdate -radix decimal /tb/rcc_up_filter_inst/i_samplesi
add wave -noupdate -radix decimal /tb/rcc_up_filter_inst/i_samplesq
add wave -noupdate -format Analog-Step -height 70 -max 16000.0 -min -16000.0 -radix decimal -subitemconfig {/tb/rcc_up_filter_inst/o_samplei(15) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(14) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(13) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(12) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(11) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(10) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(9) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(8) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(7) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(6) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(5) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(4) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(3) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(2) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(1) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(0) {-height 15 -radix decimal}} -expand -subitemconfig {/tb/rcc_up_filter_inst/o_samplei(15) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(14) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(13) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(12) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(11) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(10) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(9) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(8) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(7) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(6) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(5) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(4) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(3) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(2) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(1) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/o_samplei(0) {-height 15 -radix decimal}} /tb/rcc_up_filter_inst/o_samplei
add wave -noupdate -format Analog-Step -height 70 -max 16000.0 -min -16000.0 -radix decimal -subitemconfig {/tb/rcc_up_filter_inst/o_sampleq(15) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(14) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(13) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(12) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(11) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(10) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(9) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(8) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(7) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(6) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(5) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(4) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(3) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(2) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(1) {-radix decimal} /tb/rcc_up_filter_inst/o_sampleq(0) {-radix decimal}} /tb/rcc_up_filter_inst/o_sampleq
add wave -noupdate -radix decimal -subitemconfig {/tb/rcc_up_filter_inst/muls_i(0) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(1) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(2) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(3) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(4) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(5) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(6) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(7) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(8) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(9) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(10) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(11) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(12) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(13) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(14) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(15) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(16) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(17) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(18) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(19) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(20) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(21) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(22) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(23) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(24) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(25) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(26) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(27) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(28) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(29) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(30) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(31) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/muls_i(32) {-height 15 -radix decimal}} /tb/rcc_up_filter_inst/muls_i
add wave -noupdate -radix decimal /tb/rcc_up_filter_inst/muls_q
add wave -noupdate -radix decimal -subitemconfig {/tb/rcc_up_filter_inst/delaylinei(0) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(1) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(2) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(3) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(4) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(5) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(6) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(7) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(8) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(9) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(10) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(11) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(12) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(13) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(14) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(15) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(16) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(17) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(18) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(19) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(20) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(21) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(22) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(23) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(24) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(25) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(26) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(27) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(28) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(29) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(30) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(31) {-radix decimal} /tb/rcc_up_filter_inst/delaylinei(32) {-radix decimal}} /tb/rcc_up_filter_inst/delaylinei
add wave -noupdate -radix decimal /tb/rcc_up_filter_inst/delaylineq
add wave -noupdate -radix decimal -subitemconfig {/tb/rcc_up_filter_inst/sumsi_1(0) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(1) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(2) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(3) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(4) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(5) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(6) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(7) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(14) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(13) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(12) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(11) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(10) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(9) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(8) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(7) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(6) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(5) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(4) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(3) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(2) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(1) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(8)(0) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_1(9) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(10) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(11) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(12) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(13) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(14) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(15) {-height 15 -radix decimal} /tb/rcc_up_filter_inst/sumsi_1(16) {-height 15 -radix decimal}} /tb/rcc_up_filter_inst/sumsi_1
add wave -noupdate -radix decimal /tb/rcc_up_filter_inst/sumsq_1
add wave -noupdate -radix decimal -subitemconfig {/tb/rcc_up_filter_inst/sumsi_2(0) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(15) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(14) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(13) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(12) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(11) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(10) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(9) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(8) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(7) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(6) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(5) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(4) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(3) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(2) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(1) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(0)(0) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(1) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(2) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(3) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(4) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(5) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(6) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(7) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_2(8) {-radix decimal}} /tb/rcc_up_filter_inst/sumsi_2
add wave -noupdate -radix decimal -subitemconfig {/tb/rcc_up_filter_inst/sumsq_2(0) {-radix decimal} /tb/rcc_up_filter_inst/sumsq_2(1) {-radix decimal} /tb/rcc_up_filter_inst/sumsq_2(2) {-radix decimal} /tb/rcc_up_filter_inst/sumsq_2(3) {-radix decimal} /tb/rcc_up_filter_inst/sumsq_2(4) {-radix decimal} /tb/rcc_up_filter_inst/sumsq_2(5) {-radix decimal} /tb/rcc_up_filter_inst/sumsq_2(6) {-radix decimal} /tb/rcc_up_filter_inst/sumsq_2(7) {-radix decimal} /tb/rcc_up_filter_inst/sumsq_2(8) {-radix decimal}} /tb/rcc_up_filter_inst/sumsq_2
add wave -noupdate -radix decimal -subitemconfig {/tb/rcc_up_filter_inst/sumsi_3(0) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_3(1) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_3(2) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_3(3) {-radix decimal} /tb/rcc_up_filter_inst/sumsi_3(4) {-radix decimal}} /tb/rcc_up_filter_inst/sumsi_3
add wave -noupdate -radix decimal /tb/rcc_up_filter_inst/sumsq_3
add wave -noupdate -radix decimal /tb/rcc_up_filter_inst/sumsi_4
add wave -noupdate -radix decimal /tb/rcc_up_filter_inst/sumsq_4
add wave -noupdate -radix decimal /tb/rcc_up_filter_inst/sumsi_5
add wave -noupdate -radix decimal /tb/rcc_up_filter_inst/sumsq_5
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {99380000 ps} 0}
configure wave -namecolwidth 302
configure wave -valuecolwidth 69
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {90648431 ps} {92289057 ps}
