onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix decimal /tb/gadarg_i/clk
add wave -noupdate -radix decimal /tb/gadarg_i/reset
add wave -noupdate -radix decimal /tb/gadarg_i/i_ce
add wave -noupdate -radix decimal /tb/gadarg_i/i_samplei
add wave -noupdate -radix decimal /tb/gadarg_i/i_sampleq
add wave -noupdate -format Analog-Step -height 74 -max 29999.999999999996 -min -30000.0 -radix decimal -subitemconfig {/tb/gadarg_i/o_samplei(15) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(14) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(13) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(12) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(11) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(10) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(9) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(8) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(7) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(6) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(5) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(4) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(3) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(2) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(1) {-height 15 -radix decimal} /tb/gadarg_i/o_samplei(0) {-height 15 -radix decimal}} /tb/gadarg_i/o_samplei
add wave -noupdate -format Analog-Step -height 74 -max 29999.999999999996 -min -30000.0 -radix decimal -subitemconfig {/tb/gadarg_i/o_sampleq(15) {-radix decimal} /tb/gadarg_i/o_sampleq(14) {-radix decimal} /tb/gadarg_i/o_sampleq(13) {-radix decimal} /tb/gadarg_i/o_sampleq(12) {-radix decimal} /tb/gadarg_i/o_sampleq(11) {-radix decimal} /tb/gadarg_i/o_sampleq(10) {-radix decimal} /tb/gadarg_i/o_sampleq(9) {-radix decimal} /tb/gadarg_i/o_sampleq(8) {-radix decimal} /tb/gadarg_i/o_sampleq(7) {-radix decimal} /tb/gadarg_i/o_sampleq(6) {-radix decimal} /tb/gadarg_i/o_sampleq(5) {-radix decimal} /tb/gadarg_i/o_sampleq(4) {-radix decimal} /tb/gadarg_i/o_sampleq(3) {-radix decimal} /tb/gadarg_i/o_sampleq(2) {-radix decimal} /tb/gadarg_i/o_sampleq(1) {-radix decimal} /tb/gadarg_i/o_sampleq(0) {-radix decimal}} /tb/gadarg_i/o_sampleq
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/wr0r_div(7) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(6) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(5) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(4) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(3) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(2) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(1) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(0) {-height 15 -radix decimal}} -subitemconfig {/tb/gadarg_i/wr0r_div(7) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(6) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(5) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(4) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(3) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(2) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(1) {-height 15 -radix decimal} /tb/gadarg_i/wr0r_div(0) {-height 15 -radix decimal}} /tb/gadarg_i/wr0r_div
add wave -noupdate -radix decimal -expand -subitemconfig {/tb/gadarg_i/wr0r_div_1w(7) {-radix decimal} /tb/gadarg_i/wr0r_div_1w(6) {-radix decimal} /tb/gadarg_i/wr0r_div_1w(5) {-radix decimal} /tb/gadarg_i/wr0r_div_1w(4) {-radix decimal} /tb/gadarg_i/wr0r_div_1w(3) {-radix decimal} /tb/gadarg_i/wr0r_div_1w(2) {-radix decimal} /tb/gadarg_i/wr0r_div_1w(1) {-radix decimal} /tb/gadarg_i/wr0r_div_1w(0) {-radix decimal}} /tb/gadarg_i/wr0r_div_1w
add wave -noupdate -radix decimal /tb/gadarg_i/vi2r_mul
add wave -noupdate -radix decimal /tb/gadarg_i/vi2r_mul
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/vr2r(31) {-radix decimal} /tb/gadarg_i/vr2r(30) {-radix decimal} /tb/gadarg_i/vr2r(29) {-radix decimal} /tb/gadarg_i/vr2r(28) {-radix decimal} /tb/gadarg_i/vr2r(27) {-radix decimal} /tb/gadarg_i/vr2r(26) {-radix decimal} /tb/gadarg_i/vr2r(25) {-radix decimal} /tb/gadarg_i/vr2r(24) {-radix decimal} /tb/gadarg_i/vr2r(23) {-radix decimal} /tb/gadarg_i/vr2r(22) {-radix decimal} /tb/gadarg_i/vr2r(21) {-radix decimal} /tb/gadarg_i/vr2r(20) {-radix decimal} /tb/gadarg_i/vr2r(19) {-radix decimal} /tb/gadarg_i/vr2r(18) {-radix decimal} /tb/gadarg_i/vr2r(17) {-radix decimal} /tb/gadarg_i/vr2r(16) {-radix decimal} /tb/gadarg_i/vr2r(15) {-radix decimal} /tb/gadarg_i/vr2r(14) {-radix decimal} /tb/gadarg_i/vr2r(13) {-radix decimal} /tb/gadarg_i/vr2r(12) {-radix decimal} /tb/gadarg_i/vr2r(11) {-radix decimal} /tb/gadarg_i/vr2r(10) {-radix decimal} /tb/gadarg_i/vr2r(9) {-radix decimal} /tb/gadarg_i/vr2r(8) {-radix decimal} /tb/gadarg_i/vr2r(7) {-radix decimal} /tb/gadarg_i/vr2r(6) {-radix decimal} /tb/gadarg_i/vr2r(5) {-radix decimal} /tb/gadarg_i/vr2r(4) {-radix decimal} /tb/gadarg_i/vr2r(3) {-radix decimal} /tb/gadarg_i/vr2r(2) {-radix decimal} /tb/gadarg_i/vr2r(1) {-radix decimal} /tb/gadarg_i/vr2r(0) {-radix decimal}} /tb/gadarg_i/vr2r
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/vr3r(31) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(30) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(29) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(28) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(27) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(26) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(25) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(24) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(23) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(22) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(21) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(20) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(19) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(18) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(17) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(16) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(15) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(14) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(13) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(12) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(11) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(10) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(9) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(8) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(7) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(6) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(5) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(4) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(3) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(2) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(1) {-height 15 -radix decimal} /tb/gadarg_i/vr3r(0) {-height 15 -radix decimal}} /tb/gadarg_i/vr3r
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/delay_line_with_step_i(16) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(15) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(14) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(13) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(12) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(11) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(10) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(9) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(8) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(7) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(6) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(5) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(4) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(3) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(2) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(1) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(0) {-height 15 -radix decimal}} -subitemconfig {/tb/gadarg_i/delay_line_with_step_i(16) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(15) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(14) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(13) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(12) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(11) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(10) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(9) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(8) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(7) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(6) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(5) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(4) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(3) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(2) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(1) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_with_step_i(0) {-height 15 -radix decimal}} /tb/gadarg_i/delay_line_with_step_i
add wave -noupdate -radix decimal /tb/gadarg_i/delay_line_with_step_q
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/delay_line_i(7) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_i(6) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_i(5) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_i(4) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_i(3) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_i(2) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_i(1) {-height 15 -radix decimal} /tb/gadarg_i/delay_line_i(0) {-height 15 -radix decimal}} /tb/gadarg_i/delay_line_i
add wave -noupdate -radix decimal /tb/gadarg_i/delay_line_q
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/coefs_work(7) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(6) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(5) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(4) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(3) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(2) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(1) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(0) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal}} -expand -subitemconfig {/tb/gadarg_i/coefs_work(7) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(6) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(5) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(4) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(3) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(2) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(1) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal} /tb/gadarg_i/coefs_work(0) {-height 15 -max 500000000000.0 -min -500000000000.0 -radix decimal}} /tb/gadarg_i/coefs_work
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/coefs_ii(7) {-height 15 -radix decimal} /tb/gadarg_i/coefs_ii(6) {-height 15 -radix decimal} /tb/gadarg_i/coefs_ii(5) {-height 15 -radix decimal} /tb/gadarg_i/coefs_ii(4) {-height 15 -radix decimal} /tb/gadarg_i/coefs_ii(3) {-height 15 -radix decimal} /tb/gadarg_i/coefs_ii(2) {-height 15 -radix decimal} /tb/gadarg_i/coefs_ii(1) {-height 15 -radix decimal} /tb/gadarg_i/coefs_ii(0) {-height 15 -radix decimal}} /tb/gadarg_i/coefs_ii
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/coefs_qq(7) {-radix decimal} /tb/gadarg_i/coefs_qq(6) {-radix decimal} /tb/gadarg_i/coefs_qq(5) {-radix decimal} /tb/gadarg_i/coefs_qq(4) {-radix decimal} /tb/gadarg_i/coefs_qq(3) {-radix decimal} /tb/gadarg_i/coefs_qq(2) {-radix decimal} /tb/gadarg_i/coefs_qq(1) {-radix decimal} /tb/gadarg_i/coefs_qq(0) {-radix decimal}} /tb/gadarg_i/coefs_qq
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/coefs_iq(7) {-height 15 -radix decimal} /tb/gadarg_i/coefs_iq(6) {-height 15 -radix decimal} /tb/gadarg_i/coefs_iq(5) {-height 15 -radix decimal} /tb/gadarg_i/coefs_iq(4) {-height 15 -radix decimal} /tb/gadarg_i/coefs_iq(3) {-height 15 -radix decimal} /tb/gadarg_i/coefs_iq(2) {-height 15 -radix decimal} /tb/gadarg_i/coefs_iq(1) {-height 15 -radix decimal} /tb/gadarg_i/coefs_iq(0) {-height 15 -radix decimal}} /tb/gadarg_i/coefs_iq
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/coefs_qi(7) {-height 15 -radix decimal} /tb/gadarg_i/coefs_qi(6) {-height 15 -radix decimal} /tb/gadarg_i/coefs_qi(5) {-height 15 -radix decimal} /tb/gadarg_i/coefs_qi(4) {-height 15 -radix decimal} /tb/gadarg_i/coefs_qi(3) {-height 15 -radix decimal} /tb/gadarg_i/coefs_qi(2) {-height 15 -radix decimal} /tb/gadarg_i/coefs_qi(1) {-height 15 -radix decimal} /tb/gadarg_i/coefs_qi(0) {-height 15 -radix decimal}} /tb/gadarg_i/coefs_qi
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/c_mul_i(7) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_i(6) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_i(5) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_i(4) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_i(3) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_i(2) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_i(1) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_i(0) {-height 15 -radix decimal}} /tb/gadarg_i/c_mul_i
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/c_mul_q(7) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_q(6) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_q(5) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_q(4) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_q(3) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_q(2) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_q(1) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_q(0) {-height 15 -radix decimal}} /tb/gadarg_i/c_mul_q
add wave -noupdate -radix unsigned /tb/gadarg_i/step_cnt
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/c_mul_sum_i(15) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(14) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(13) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(12) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(11) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(10) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(9) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(8) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(7) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(6) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(5) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(4) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(3) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(2) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(1) {-height 15 -radix decimal} /tb/gadarg_i/c_mul_sum_i(0) {-height 15 -radix decimal}} /tb/gadarg_i/c_mul_sum_i
add wave -noupdate -radix decimal /tb/gadarg_i/c_mul_sum_q
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/sumed_muls_i(15) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(14) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(13) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(12) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(11) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(10) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(9) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(8) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(7) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(6) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(5) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(4) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(3) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(2) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(1) {-height 15 -radix decimal} /tb/gadarg_i/sumed_muls_i(0) {-height 15 -radix decimal}} /tb/gadarg_i/sumed_muls_i
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/sumed_muls_q(15) {-radix decimal} /tb/gadarg_i/sumed_muls_q(14) {-radix decimal} /tb/gadarg_i/sumed_muls_q(13) {-radix decimal} /tb/gadarg_i/sumed_muls_q(12) {-radix decimal} /tb/gadarg_i/sumed_muls_q(11) {-radix decimal} /tb/gadarg_i/sumed_muls_q(10) {-radix decimal} /tb/gadarg_i/sumed_muls_q(9) {-radix decimal} /tb/gadarg_i/sumed_muls_q(8) {-radix decimal} /tb/gadarg_i/sumed_muls_q(7) {-radix decimal} /tb/gadarg_i/sumed_muls_q(6) {-radix decimal} /tb/gadarg_i/sumed_muls_q(5) {-radix decimal} /tb/gadarg_i/sumed_muls_q(4) {-radix decimal} /tb/gadarg_i/sumed_muls_q(3) {-radix decimal} /tb/gadarg_i/sumed_muls_q(2) {-radix decimal} /tb/gadarg_i/sumed_muls_q(1) {-radix decimal} /tb/gadarg_i/sumed_muls_q(0) {-radix decimal}} /tb/gadarg_i/sumed_muls_q
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/sq_sumed_muls_i(31) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(30) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(29) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(28) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(27) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(26) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(25) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(24) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(23) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(22) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(21) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(20) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(19) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(18) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(17) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(16) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(15) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(14) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(13) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(12) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(11) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(10) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(9) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(8) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(7) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(6) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(5) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(4) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(3) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(2) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(1) {-height 15 -radix decimal} /tb/gadarg_i/sq_sumed_muls_i(0) {-height 15 -radix decimal}} /tb/gadarg_i/sq_sumed_muls_i
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/sq_sumed_muls_q(31) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(30) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(29) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(28) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(27) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(26) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(25) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(24) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(23) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(22) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(21) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(20) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(19) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(18) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(17) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(16) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(15) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(14) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(13) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(12) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(11) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(10) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(9) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(8) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(7) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(6) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(5) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(4) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(3) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(2) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(1) {-radix decimal} /tb/gadarg_i/sq_sumed_muls_q(0) {-radix decimal}} /tb/gadarg_i/sq_sumed_muls_q
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/vr2r(31) {-radix decimal} /tb/gadarg_i/vr2r(30) {-radix decimal} /tb/gadarg_i/vr2r(29) {-radix decimal} /tb/gadarg_i/vr2r(28) {-radix decimal} /tb/gadarg_i/vr2r(27) {-radix decimal} /tb/gadarg_i/vr2r(26) {-radix decimal} /tb/gadarg_i/vr2r(25) {-radix decimal} /tb/gadarg_i/vr2r(24) {-radix decimal} /tb/gadarg_i/vr2r(23) {-radix decimal} /tb/gadarg_i/vr2r(22) {-radix decimal} /tb/gadarg_i/vr2r(21) {-radix decimal} /tb/gadarg_i/vr2r(20) {-radix decimal} /tb/gadarg_i/vr2r(19) {-radix decimal} /tb/gadarg_i/vr2r(18) {-radix decimal} /tb/gadarg_i/vr2r(17) {-radix decimal} /tb/gadarg_i/vr2r(16) {-radix decimal} /tb/gadarg_i/vr2r(15) {-radix decimal} /tb/gadarg_i/vr2r(14) {-radix decimal} /tb/gadarg_i/vr2r(13) {-radix decimal} /tb/gadarg_i/vr2r(12) {-radix decimal} /tb/gadarg_i/vr2r(11) {-radix decimal} /tb/gadarg_i/vr2r(10) {-radix decimal} /tb/gadarg_i/vr2r(9) {-radix decimal} /tb/gadarg_i/vr2r(8) {-radix decimal} /tb/gadarg_i/vr2r(7) {-radix decimal} /tb/gadarg_i/vr2r(6) {-radix decimal} /tb/gadarg_i/vr2r(5) {-radix decimal} /tb/gadarg_i/vr2r(4) {-radix decimal} /tb/gadarg_i/vr2r(3) {-radix decimal} /tb/gadarg_i/vr2r(2) {-radix decimal} /tb/gadarg_i/vr2r(1) {-radix decimal} /tb/gadarg_i/vr2r(0) {-radix decimal}} /tb/gadarg_i/vr2r
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/vi2r(31) {-radix decimal} /tb/gadarg_i/vi2r(30) {-radix decimal} /tb/gadarg_i/vi2r(29) {-radix decimal} /tb/gadarg_i/vi2r(28) {-radix decimal} /tb/gadarg_i/vi2r(27) {-radix decimal} /tb/gadarg_i/vi2r(26) {-radix decimal} /tb/gadarg_i/vi2r(25) {-radix decimal} /tb/gadarg_i/vi2r(24) {-radix decimal} /tb/gadarg_i/vi2r(23) {-radix decimal} /tb/gadarg_i/vi2r(22) {-radix decimal} /tb/gadarg_i/vi2r(21) {-radix decimal} /tb/gadarg_i/vi2r(20) {-radix decimal} /tb/gadarg_i/vi2r(19) {-radix decimal} /tb/gadarg_i/vi2r(18) {-radix decimal} /tb/gadarg_i/vi2r(17) {-radix decimal} /tb/gadarg_i/vi2r(16) {-radix decimal} /tb/gadarg_i/vi2r(15) {-radix decimal} /tb/gadarg_i/vi2r(14) {-radix decimal} /tb/gadarg_i/vi2r(13) {-radix decimal} /tb/gadarg_i/vi2r(12) {-radix decimal} /tb/gadarg_i/vi2r(11) {-radix decimal} /tb/gadarg_i/vi2r(10) {-radix decimal} /tb/gadarg_i/vi2r(9) {-radix decimal} /tb/gadarg_i/vi2r(8) {-radix decimal} /tb/gadarg_i/vi2r(7) {-radix decimal} /tb/gadarg_i/vi2r(6) {-radix decimal} /tb/gadarg_i/vi2r(5) {-radix decimal} /tb/gadarg_i/vi2r(4) {-radix decimal} /tb/gadarg_i/vi2r(3) {-radix decimal} /tb/gadarg_i/vi2r(2) {-radix decimal} /tb/gadarg_i/vi2r(1) {-radix decimal} /tb/gadarg_i/vi2r(0) {-radix decimal}} /tb/gadarg_i/vi2r
add wave -noupdate -radix decimal /tb/gadarg_i/vr2i
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/vr3i(31) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(30) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(29) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(28) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(27) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(26) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(25) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(24) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(23) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(22) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(21) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(20) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(19) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(18) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(17) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(16) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(15) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(14) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(13) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(12) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(11) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(10) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(9) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(8) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(7) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(6) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(5) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(4) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(3) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(2) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(1) {-height 15 -radix decimal} /tb/gadarg_i/vr3i(0) {-height 15 -radix decimal}} /tb/gadarg_i/vr3i
add wave -noupdate -radix decimal /tb/gadarg_i/vi3r
add wave -noupdate -radix decimal /tb/gadarg_i/vi2i
add wave -noupdate -radix decimal /tb/gadarg_i/vi3i
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/wr0i_div(7) {-radix decimal} /tb/gadarg_i/wr0i_div(6) {-radix decimal} /tb/gadarg_i/wr0i_div(5) {-radix decimal} /tb/gadarg_i/wr0i_div(4) {-radix decimal} /tb/gadarg_i/wr0i_div(3) {-radix decimal} /tb/gadarg_i/wr0i_div(2) {-radix decimal} /tb/gadarg_i/wr0i_div(1) {-radix decimal} /tb/gadarg_i/wr0i_div(0) {-radix decimal}} /tb/gadarg_i/wr0i_div
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/wi0r_div(7) {-radix decimal} /tb/gadarg_i/wi0r_div(6) {-radix decimal} /tb/gadarg_i/wi0r_div(5) {-radix decimal} /tb/gadarg_i/wi0r_div(4) {-radix decimal} /tb/gadarg_i/wi0r_div(3) {-radix decimal} /tb/gadarg_i/wi0r_div(2) {-radix decimal} /tb/gadarg_i/wi0r_div(1) {-radix decimal} /tb/gadarg_i/wi0r_div(0) {-radix decimal}} /tb/gadarg_i/wi0r_div
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/wi0i_div(7) {-radix decimal} /tb/gadarg_i/wi0i_div(6) {-radix decimal} /tb/gadarg_i/wi0i_div(5) {-radix decimal} /tb/gadarg_i/wi0i_div(4) {-radix decimal} /tb/gadarg_i/wi0i_div(3) {-radix decimal} /tb/gadarg_i/wi0i_div(2) {-radix decimal} /tb/gadarg_i/wi0i_div(1) {-radix decimal} /tb/gadarg_i/wi0i_div(0) {-radix decimal}} /tb/gadarg_i/wi0i_div
add wave -noupdate -radix decimal -subitemconfig {/tb/gadarg_i/wrr(7) {-height 15 -radix decimal} /tb/gadarg_i/wrr(6) {-height 15 -radix decimal} /tb/gadarg_i/wrr(5) {-height 15 -radix decimal} /tb/gadarg_i/wrr(4) {-height 15 -radix decimal} /tb/gadarg_i/wrr(3) {-height 15 -radix decimal} /tb/gadarg_i/wrr(2) {-height 15 -radix decimal} /tb/gadarg_i/wrr(1) {-height 15 -radix decimal} /tb/gadarg_i/wrr(0) {-height 15 -radix decimal}} -expand -subitemconfig {/tb/gadarg_i/wrr(7) {-height 15 -radix decimal} /tb/gadarg_i/wrr(6) {-height 15 -radix decimal} /tb/gadarg_i/wrr(5) {-height 15 -radix decimal} /tb/gadarg_i/wrr(4) {-height 15 -radix decimal} /tb/gadarg_i/wrr(3) {-height 15 -radix decimal} /tb/gadarg_i/wrr(2) {-height 15 -radix decimal} /tb/gadarg_i/wrr(1) {-height 15 -radix decimal} /tb/gadarg_i/wrr(0) {-height 15 -radix decimal}} /tb/gadarg_i/wrr
add wave -noupdate -radix decimal /tb/gadarg_i/wri
add wave -noupdate -radix decimal /tb/gadarg_i/wir
add wave -noupdate -radix decimal /tb/gadarg_i/wii
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {271344 ps} 0}
configure wave -namecolwidth 250
configure wave -valuecolwidth 92
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {174060 ps} {432429 ps}
